crew_name: "KnowledgeTestCrew"
usecase: "integration_test_knowledge"
module_name: "IntegrationParams"

crews:
  "KnowledgeTestCrew":
    steps:
      - task_key: "knowledge_task"
        agent_key: "knowledge_agent"
        task_file: "/home/dell/PycharmProjects/Amsha/src/nikhil/amsha/example/crew_forge/config/task_knowledge.yaml"
        agent_file: "/home/dell/PycharmProjects/Amsha/src/nikhil/amsha/example/crew_forge/config/agent_basic.yaml"
        # We attach knowledge specifically to this agent step
        knowledge_sources: 
          - "/home/dell/PycharmProjects/Amsha/src/nikhil/amsha/example/crew_forge/data/knowledge.md"

knowledge_sources: []
