[project]
name = "Amsha"
version = "2.0.0"
description = "Common config and crew AI helpers"
dependencies = [
    "pandas == 2.3.2",
    "openpyxl == 3.1.5",
    "pymongo == 4.11.3",
    "pydantic == 2.11.9",
    "git+https://github.com/your-org/vak.git@main#egg=Vak"
]


[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]