crew_name: "Copy Crew"
usecase: "copy"
module_name: "copy"
output_filepath: "E:/Python/Amsha/.Amsha/output/intermediate/crew/crew_configurations.json"

crews:
  copy_crew:
#    knowledge_sources:
#      - "E:/Python/Amsha/knowledge/reference.md"
#      - "./docs/style_guide.txt"
#    input:
#      source: "file"
#      path: "E:/Python/data/raw/features.json"
    steps:
      - task_key: "ad_copy_task"
        agent_key: "copywriter_agent"
        task_file: "E:/Python/Amsha/src/nikhil/amsha/crew_forge/example/example_config/crew_configs/copy/tasks/ad_copy_task.yaml"
        agent_file: "E:/Python/Amsha/src/nikhil/amsha/crew_forge/example/example_config/crew_configs/copy/agents/copywriter_agent.yaml"
#        knowledge_sources:
#          - "E:/Python/Amsha/knowledge/reference.md"
#      - "./data/competitor_analysis.pdf"
#      - "./data/user_feedback.txt"


pipeline:
  - "copy_crew"

